version: '3.8'
services:
  client-frontend:
    image: frontend:0.0.1
    build:
      context: ../FinMangerFrontEnd
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8081:8081'
    volumes:
      - /app/node_modules
      - ./frontend:/app

  client-backend:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://db:1521/bd1

  service-db:
    image: openjdk:11-jre-slim
    command: ["java", "-cp", "/usr/share/h2/h2-1.4.200.jar", "org.h2.tools.Server", "-ifNotExists"]
    volumes:
      - "./data:/data"
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - "15432:5432"
    restart: unless-stopped

volumes:
  db-data: