version: '3.8'
services:
  client-frontend:
    image: orcxus/fin_man_front_end:latest
    ports:
      - '8081:8081'
    networks:
      - finman-inner-network

  client-backend:
    image: orcxus/fin_man_back_end:latest
    depends_on:
      - service-db
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/db2
    networks:
      - finman-inner-network

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
        - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
        - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - finman-inner-network

volumes:
  db-data:
  pgadmin-data:

networks:
  finman-inner-network:
