  server:
    port: 8080
  
  # for deploy:
  spring:
    profiles:
      active: {SPRING_PROFILES_ACTIVE}
    jpa:
      properties:
        hibernate:
          format_sql: true
          default_batch_fetch_size: 100
          jdbc:
            batch_size: 100
            fetch_size: 1000
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
    logging:
      level:
        org.hibernate.SQL: OFF
        org.hibernate.type.descriptor.sql: OFF
        org.hibernate.engine.jdbc.batch: OFF
  path: /console
  
  # app properties
  app:
    jwtCookieName: token
    jwtSecret: applicationSecretKeyapplicationSecretKeyapplicationSecretKey
    jwtExpirationMs: 86400000
