spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:file:./bd1
    driverClassName: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
        # Logging settings for local
#      logging:
#       level:
#         org.hibernate.SQL: DEBUG
#         org.hibernate.type.descriptor.sql: TRACE

  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false